---
- name: Apply RHEL 9 STIG to target hosts
  hosts: "{{ run_against }}" # Replace with your target host group or server IP/hostname
  become: yes # The STIG role requires elevated privileges

  tasks:

    - name: Apply the CAT I fixes for the RHEL 9 STIG
      ansible.builtin.include_role:
        name: ansible-role-rhel9-stig
      vars:
        high_severity: true # Ensure CAT I fixes are applied

    - name: Reboot the system if required
      ansible.builtin.reboot:
        msg: "Rebooting to apply RHEL 9 STIG changes"
        connect_timeout: 5
        reboot_timeout: 600
      when: ansible_facts['reboot_required'] | bool